CREATE TABLE GRANT_STATUSES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    STATUS VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO GRANT_STATUSES VALUES (DEFAULT, "Pending");
INSERT INTO GRANT_STATUSES VALUES (DEFAULT, "Awarded");

CREATE TABLE GRANT_TYPES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    GRANT_TYPE VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZATIONS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ORGANIZATION TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PROJECTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PROJECT MEDIUMTEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE LOCATIONS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    LOCATION VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STRATEGIC_PRIORITIES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    STRATEGIC_PRIORITY VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STRATEGIC_RESULTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    STRATEGIC_RESULT VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GRANTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    GRANT_STATUS_ID BIGINT NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL,
    GRANT_TYPE_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL,
    PROJECT_ID BIGINT NOT NULL,
    AMOUNT BIGINT NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    STRATEGIC_PRIORITY_ID BIGINT NOT NULL,
    STRATEGIC_RESULT_ID BIGINT NOT NULL,
    TOTAL_NUMBER_SERVED INTEGER NOT NULL,
    NUMBER_NATIVE_HAWAIIANS_SERVED INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GRANT_STATUS_ID) REFERENCES GRANT_STATUSES(ID),
    FOREIGN KEY (GRANT_TYPE_ID) REFERENCES GRANT_TYPES(ID),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID),
    FOREIGN KEY (STRATEGIC_PRIORITY_ID) REFERENCES STRATEGIC_PRIORITIES(ID),
    FOREIGN KEY (STRATEGIC_RESULT_ID) REFERENCES STRATEGIC_RESULTS(ID)
);

